version: '3.1'

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  intake-service:
    image: taskprocessing-intake-service:0.0.1
    restart: on-failure
    depends_on:
      - kafka
      - postgres
    ports:
      - '8080:8080'
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - DB_URL=jdbc:postgresql://postgres:5432/taskdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - TASK_TOPIC_NAME=task-topic
      - TASK_TOPIC_PARTITIONS=1
      - TASK_TOPIC_REPLICATION_FACTOR=1
  processor-service:
    image: taskprocessing-processor-service:0.0.1
    restart: on-failure
    depends_on:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - DB_URL=jdbc:postgresql://postgres:5432/taskdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - TASK_TOPIC_NAME=task-topic
      - TASK_CONSUMER_GROUP_ID=processor-consumer-group
      - TASK_DELAY=5000
volumes:
  postgres_data: