spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
kafka:
  task:
    topic:
      name: ${TASK_TOPIC_NAME}
      partitions: {TASK_TOPIC_PARTITIONS}
      replication-factor: ${TASK_TOPIC_REPLICATION_FACTOR}
